[WIP] Persistent transaction IDs
restorando/log_weasel pull request #1
Opened 2017-10-10 18:53 UTC by lipusal

2017-10-23 20:36 UTC, nicoayala requested changes
Lo veo bien! Van unos comments para unos cambios.

2017-10-23 20:36 UTC, nicoayala commented on lib/log_weasel/middleware.rb
> +  TRANSACTION_ID_HEADER = 'X_LOGWEASEL_TRANSACTION_ID'
Creo que seria mejor mantener el nombre del header genérico: `X_TRANSACTION_ID` (estaria bueno que sea configurable, ver [LogWeasel.config](https://github.com/carbonfive/log_weasel/blob/master/lib/log_weasel.rb))
Desde el punto de vista de un cliente que le pega a `redo-api` enviando el header por ejemplo, porque deberia saber que usamos `log_weasel`?

2017-10-23 20:36 UTC, nicoayala commented on lib/log_weasel/middleware.rb
> +    transaction_id = env.fetch("HTTP_#{TRANSACTION_ID_HEADER}", nil)
Esto lo podemos resumir a:
```ruby
transaction_id = env.fetch("HTTP_#{TRANSACTION_ID_HEADER}", LogWeasel::Transaction.create(key))
LogWeasel::Transaction.id = transaction_id
```

2017-10-24 18:41 UTC, lipusal commented
@nicoayala Gracias por tus comments, me di la libertad de ir un poco más allá con la configuración

- El header es configurable
- Toda la gema se puede prender y apagar (algo así tiene `lograge`)
- Se puede pasar un generador de IDs custom, por default usa el que ya tiene
- Se puede configurar que si no hay transaction ID que no lo genere

2017-10-24 18:44 UTC, lipusal commented
También saqué eso de que prefije los IDs con una clave, no sé para que estaba. Creo que era para si un mismo thread corría más de una aplicación con `log_weasel` para evitar clashes? Creo que no hace falta, si te parece lo vuelvo a poner

2017-10-26 11:46 UTC, nicoayala requested changes
Lo veo casi listo, van algunos comments:
* Sacaría la dependencia con `hashie` y usaria la clase `Config` como estaba antes.
* No me queda claro si es necesario el atributo `key` que mencionás, parecería que no, pero miremos algun log generado sin `key` para entender un poco mejor.

2017-10-30 15:39 UTC, lipusal commented
@nicoayala Parece que se usaba como [prefijo de las transaction IDs](https://github.com/restorando/log_weasel/blob/b26da8d4c33dc7071b2336b6868252ebca52b403/lib/log_weasel/transaction.rb#L11), creo que no hace falta. Se utilizaba porque creo que un mismo thread podía correr varias aplicaciones distintas con log weasel, ahora ya no. De todas maneras sí, vamos a hacer pruebas a ver cómo cambia.
Btw yay Travis 🎉

2017-10-30 17:29 UTC, lipusal commented on lib/log_weasel/transaction.rb
> +    def self.set_or_create(id = nil)
Quizá hay un mejor nombre para este método? A Rubocop no le gusta el prefijo `set_`

2020-05-12 16:59 UTC, lipusal commented
This has been showing up in my PR feed for years now so I'm gonna close it =P

2020-05-12 16:59 UTC, closed without merging